/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.beatoven.beatoven.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import uk.ac.kcl.beatoven.ui.internal.BeatovenActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BeatovenExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(BeatovenActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		BeatovenActivator activator = BeatovenActivator.getInstance();
		return activator != null ? activator.getInjector(BeatovenActivator.UK_AC_KCL_BEATOVEN_BEATOVEN_BEATOVEN) : null;
	}

}
