/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.beatoven.beatoven.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BeatovenUiModule extends AbstractBeatovenUiModule {

	public BeatovenUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
