/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.beatoven.beatoven.ide;


/**
 * Use this class to register ide components.
 */
public class BeatovenIdeModule extends AbstractBeatovenIdeModule {
}
